In [2]:
import numpy as np

In [4]:
list=[1,2,3,4,5,500]
sample_list=np.array(list)
sample_list

array([  1,   2,   3,   4,   5, 500])

In [5]:
np.mean(sample_list)

85.83333333333333

In [6]:
np.median(sample_list)

3.5

# create an array

In [7]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [9]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(5,28)    # numbers 5 to 27 with spacing as 1 # arange not aRRange

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [13]:
np.arange(5,35,6)  # 6 is the step size

array([ 5, 11, 17, 23, 29])

In [14]:
np.zeros(6)      # zeros with float data

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros(6, dtype=int)     #zeros with int data

array([0, 0, 0, 0, 0, 0])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [19]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [21]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [22]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [25]:
np.random.rand(2,4)

array([[0.42069943, 0.44095274, 0.59506802, 0.70767954],
       [0.46581389, 0.67500756, 0.40441589, 0.67077436]])

In [26]:
np.random.randn(2,4)

array([[ 0.83982761,  0.66811096,  0.96005976,  1.06283441],
       [-0.61060887, -0.67819996,  2.85833173,  0.54834635]])

In [27]:
np.random.rand(2,5)

array([[0.43722486, 0.87108719, 0.9260072 , 0.63817444, 0.98149929],
       [0.49481081, 0.92926608, 0.79444942, 0.29050214, 0.89923601]])

In [29]:
np.random.randint(0,10,15)

array([5, 8, 4, 2, 3, 9, 2, 1, 5, 8, 0, 0, 2, 6, 2])

In [30]:
np.random.randint(20,56,100)

array([37, 45, 44, 38, 47, 21, 35, 36, 32, 36, 51, 24, 25, 54, 48, 42, 21,
       42, 50, 24, 41, 22, 32, 39, 40, 20, 32, 28, 43, 20, 24, 55, 33, 39,
       42, 37, 23, 24, 54, 48, 24, 28, 26, 49, 31, 49, 46, 42, 32, 34, 33,
       55, 55, 41, 37, 41, 22, 29, 44, 27, 34, 22, 26, 48, 43, 25, 40, 37,
       54, 28, 36, 29, 43, 34, 22, 34, 35, 55, 29, 50, 54, 48, 52, 37, 32,
       38, 43, 25, 44, 48, 35, 35, 24, 20, 49, 46, 24, 30, 38, 20])

In [33]:
np.random.randint(2,50)

25

In [34]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [35]:
rand_array=np.random.randint(0,10,5)
rand_array

array([1, 7, 4, 4, 4])

In [36]:
sample_array.min()  # minimum value of array

2

In [37]:
sample_array.argmin() #indexvalue of min value

0

In [41]:
rand_array.max()

7

In [42]:
rand_array.argmax()

1

In [54]:
import numpy as np

In [44]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
a.T          # Transpose of identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
a=np.random.rand(2,3)
a

array([[0.79432062, 0.27624081, 0.74687572],
       [0.1924599 , 0.31230859, 0.01134905]])

In [48]:
a.T

array([[0.79432062, 0.1924599 ],
       [0.27624081, 0.31230859],
       [0.74687572, 0.01134905]])

In [57]:
import numpy as np

In [59]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [60]:
sample_array=sample_array.reshape(3,6)
sample_array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [61]:
sample_array[1]=100
sample_array

array([[ 10,  11,  12,  13,  14,  15],
       [100, 100, 100, 100, 100, 100],
       [ 22,  23,  24,  25,  26,  27]])

In [62]:
sample_array=np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [63]:
sample_array[1:12]  #elements from index position 1 to 12 are taken from sample_array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [64]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [65]:
sample_array[:]=1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

# Two dimensional array

In [68]:
import numpy as np

In [69]:
sample_matrix=np.array(([24,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [70]:
sample_matrix[2][2]

24

In [71]:
sample_matrix[1][2]

54

In [72]:
sample_matrix[:,2]

array([ 2, 54, 24])

In [73]:
sample_matrix[1,1]

2

In [81]:
sample_matrix[0:2,0:4]

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [88]:
sample_matrix[0:1,1:3]

array([[13,  2]])

In [89]:
sample_matrix[1:,2:]   #first row onwards and 2nd column onwards

array([[54, 65],
       [24,  7]])

In [90]:
sample_matrix[2] # whole 3rd row

array([56, 76, 24,  7])

In [91]:
import numpy as np


In [92]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [93]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [94]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [95]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [96]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [97]:
np.max(sample_array)

30

In [98]:
np.min(sample_array)

1

In [99]:
np.std(sample_array)

8.65544144839919

In [100]:
np.var(sample_array)

74.91666666666667

In [101]:
np.mean(sample_array)

15.5

In [102]:
array=np.random.randn(3,4) ### normal distribution
array

array([[-1.05946835, -0.80614756, -0.66886956,  0.57181228],
       [ 0.51765768,  0.96358164, -1.53220042,  0.8317739 ],
       [-0.40457526, -0.45453523,  0.37879337,  0.05956102]])

In [103]:
np.round(array,decimals=3)

array([[-1.059, -0.806, -0.669,  0.572],
       [ 0.518,  0.964, -1.532,  0.832],
       [-0.405, -0.455,  0.379,  0.06 ]])

In [104]:
sports=np.array(['golf','cricket','fball','cricket','basketball'])
np.unique(sports)

array(['basketball', 'cricket', 'fball', 'golf'], dtype='<U10')

# Pandas

In [ ]:
#for reading a dataset

In [105]:
import pandas as pd
df=pd.read_csv('occupation')

FileNotFoundError: [Errno 2] No such file or directory: 'occupation'